[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
solc-optimizer = true
solc-optimizer-runs = 99999
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[profile.default.ir]
enabled = true

[rpc_endpoints]
polygon-mumbai = "${POLYGON_MUMBAI_RPC}"

[etherscan]
polygon-mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
